on:
  schedule:
    - cron: '37 13 * * *'
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Profile Readme Stats
      uses: teoxoy/profile-readme-stats@v1.2
      with:
        token: ${{ secrets.USER_TOKEN }}
    - name: Update README.md
      run: |
        if [[ "$(git status --porcelain)" != "" ]]; then
        git config user.name github-actions[bot]
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
        git add README.md
        git commit -m "[CI] Update README -- trigger $(date +%D)"
        git push
        fi
