name: Github Readme Template
on:
  schedule: [{cron: "*/45 * * * *"}]
  push: {branches: ["master", "main"]}
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }} # gh token
          user: iomonad
          template: classic
          base: activity, repositories
          config_animated: yes
          config_timezone: Europe/Paris
          plugin_activity: no
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_threshold: 0.2%
